#!C:\Users\Lenovo\Documents\JupyterNotebook\AIO 2025\W12_Streamlit\aio2025_streamlit\py310_env\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
